### PR TITLE
Review of changes in 0.4.1

### PR DESCRIPTION
**Pull request by jaredbeck**
Hopefully it saves someone else some time!

### CODE REVIEW

**Comment by jaredbeck** [comment]
@zzak Two month ping.  Any objections?

**Comment by zzak** [comment]
Could you add a link to this for the 0.4.0 release (for now?): https://github.com/voloko/sdoc/compare/v0.3.20...v0.4.0

**Comment by jaredbeck** [comment]
> Could you add a link to this for the 0.4.0 release

Added.

**Comment by zzak** [comment]
@jaredbeck Thank you!

**Pull request merged**
